name: Android CI
on:
  push:
    branches:
      - 'features-xyz'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ➡️ THIS IS THE CRITICAL CHANGE ⬅️
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Recommended distribution for better compatibility
          java-version: '17'      # Specify Java 17 for AGP 8.x
          cache: 'gradle'         # Speeds up your build by caching dependencies

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests and Build Debug APK
        run: ./gradlew clean build
