name: Build Debug APK

on:
  push:
    branches:
      - dev
      - 'features-revenuecat*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug APK
        run: ./gradlew assembleDebug
